# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  #- go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    goarm:
      - 7
archives:
  - replacements:
      darwin: Macos
      linux: Linux
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - config_example.json
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
